# Generated by Django 4.2 on 2023-08-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('F_name', models.CharField(max_length=100)),
                ('I_name', models.CharField(max_length=500)),
                ('Batch', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='student_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub1', models.IntegerField()),
                ('Sub2', models.IntegerField()),
                ('Sub3', models.IntegerField()),
                ('Sub4', models.IntegerField()),
            ],
        ),
    ]
